title: "Shreemann Mishra"
description: "Portfolio | Credit Risk | Data Science"
baseurl: ""
url: "https://shreemann.github.io"

remote_theme: daviddarnes/garth

author:
  name: "Shreemann Mishra"
  email: "shreem2412@gmail.com"

permalink: pretty
paginate: 6
